spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/14c021dd-6b1d-423e-a9f9-e59b17394821/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=api://ac0cd280-33b6-4d33-ae42-aa056c7029fa,ac0cd280-33b6-4d33-ae42-aa056c7029fa

logging.level.org.springframework.security=DEBUG

server.port=8081

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}


app.rabbitmq.pedidos-exchange=pedidos.exchange
app.rabbitmq.routing-key-pedido-creado=pedido.creado