spring.datasource.url=jdbc:mysql://3.93.197.165:3306/pedidos360
spring.datasource.username=pedidos_app
spring.datasource.password=pedidos360pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/14c021dd-6b1d-423e-a9f9-e59b17394821/v2.0

server.port=8081
