spring.datasource.url=jdbc:mysql://100.61.146.218:3306/pedidos360
spring.datasource.username=pedidos_app
spring.datasource.password=PEDIDOS360pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.security.oauth2.resourceserver.jwt.audiences=api://ac0cd280-33b6-4d33-ae42-aa056c7029fa
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://sts.windows.net/14c021dd-6b1d-423e-a9f9-e59b17394821/

server.port=8084